# Generated by Django 6.0.6 on 2026-06-30 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='carne',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='gps_location',
            field=models.CharField(blank=True, help_text='Example: 9.9281, -84.0907', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='lawyer_photos/'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawyer',
            name='webpage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
